//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ollon.VisualStudio.Shell.Attributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ollon.VisualStudio.Shell.Attributes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Abort.
        /// </summary>
        internal static string AbortCaption {
            get {
                return ResourceManager.GetString("AbortCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string is not a valid value for the argument &apos;{0}&apos;..
        /// </summary>
        internal static string Argument_EmptyString {
            get {
                return ResourceManager.GetString("Argument_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Guid..
        /// </summary>
        internal static string Argument_InvalidGuid {
            get {
                return ResourceManager.GetString("Argument_InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService..
        /// </summary>
        internal static string AsyncPackage_CannotCallGetServiceFromBackgroundThread {
            get {
                return ResourceManager.GetString("AsyncPackage_CannotCallGetServiceFromBackgroundThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register the {0} file extension, you must prefix the extension with a &apos;.&apos;..
        /// </summary>
        internal static string Attributes_ExtensionNeedsDot {
            get {
                return ResourceManager.GetString("Attributes_ExtensionNeedsDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factoryType must be of one of those type: Type, Guid, string (representing a Guid)..
        /// </summary>
        internal static string Attributes_InvalidFactoryType {
            get {
                return ResourceManager.GetString("Attributes_InvalidFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project guid provided, but it is needed to register the extension for EditorFactoryNotify..
        /// </summary>
        internal static string Attributes_NoPrjForEditorFactoryNotify {
            get {
                return ResourceManager.GetString("Attributes_NoPrjForEditorFactoryNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Product Name was specified.  To register as an Installed Product, a Product Name is required..
        /// </summary>
        internal static string Attributes_ProductNameNotSpecified {
            get {
                return ResourceManager.GetString("Attributes_ProductNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown docking style: {0}..
        /// </summary>
        internal static string Attributes_UnknownDockingStyle {
            get {
                return ResourceManager.GetString("Attributes_UnknownDockingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown relative position: {0}..
        /// </summary>
        internal static string Attributes_UnknownPosition {
            get {
                return ResourceManager.GetString("Attributes_UnknownPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load specified assembly: &apos;{0}&apos; reason: {1}.
        /// </summary>
        internal static string BinRedir_CouldNotLoadAssembly {
            get {
                return ResourceManager.GetString("BinRedir_CouldNotLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value specified for {0}..
        /// </summary>
        internal static string BinRedir_Field_Invalid {
            get {
                return ResourceManager.GetString("BinRedir_Field_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not specified, or could not be inferred from the target Assembly..
        /// </summary>
        internal static string BinRedir_Field_NotFound {
            get {
                return ResourceManager.GetString("BinRedir_Field_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldVersionLowerBound is greater than OldVersionUpperBound..
        /// </summary>
        internal static string BinRedir_LowerGreaterUpper {
            get {
                return ResourceManager.GetString("BinRedir_LowerGreaterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute should be applied to an assembly..
        /// </summary>
        internal static string BinRedir_NoAssembly {
            get {
                return ResourceManager.GetString("BinRedir_NoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldVersion is greater than NewVersion..
        /// </summary>
        internal static string BinRedir_OldGreaterNew {
            get {
                return ResourceManager.GetString("BinRedir_OldGreaterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the operation you requested....
        /// </summary>
        internal static string CommonMessagePumpDefaultWaitStatusBarText {
            get {
                return ResourceManager.GetString("CommonMessagePumpDefaultWaitStatusBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation you requested is taking longer than expected to complete. This dialog will close when the action completes..
        /// </summary>
        internal static string CommonMessagePumpDefaultWaitText {
            get {
                return ResourceManager.GetString("CommonMessagePumpDefaultWaitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert back to a Visibility value because {0} does not exclusively map to VisibilityIfTrue or VisibilityIfFalse..
        /// </summary>
        internal static string Error_BooleanToCustomVisibility {
            get {
                return ResourceManager.GetString("Error_BooleanToCustomVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a new search query parser..
        /// </summary>
        internal static string Error_CannotCreateSearchQueryParser {
            get {
                return ResourceManager.GetString("Error_CannotCreateSearchQueryParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get or create settings list..
        /// </summary>
        internal static string Error_CouldNotGetOrCreateSettingsList {
            get {
                return ResourceManager.GetString("Error_CouldNotGetOrCreateSettingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not populate Remote Code Container properties..
        /// </summary>
        internal static string Error_CouldNotPopulateRemoteCodeContainerProperties {
            get {
                return ResourceManager.GetString("Error_CouldNotPopulateRemoteCodeContainerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start a search with a query for a string that is null, empty or consisting only of white-space characters..
        /// </summary>
        internal static string Error_InvalidEmptySearchQuery {
            get {
                return ResourceManager.GetString("Error_InvalidEmptySearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path or file name &quot;{0}&quot; contains one or more invalid characters.
        /// </summary>
        internal static string Error_InvalidFilenameCharacters {
            get {
                return ResourceManager.GetString("Error_InvalidFilenameCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve service {0}..
        /// </summary>
        internal static string Flavor_FailedToGetService {
            get {
                return ResourceManager.GetString("Flavor_FailedToGetService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting an array of size greater than zero..
        /// </summary>
        internal static string General_ArraySizeShouldBeAtLeast1 {
            get {
                return ResourceManager.GetString("General_ArraySizeShouldBeAtLeast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected string that is not empty..
        /// </summary>
        internal static string General_ExpectedNonEmptyString {
            get {
                return ResourceManager.GetString("General_ExpectedNonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected object of type {0}..
        /// </summary>
        internal static string General_InvalidType {
            get {
                return ResourceManager.GetString("General_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &apos;{0}&apos; must be installed for this feature to work.  Ensure that this service is available..
        /// </summary>
        internal static string General_MissingService {
            get {
                return ResourceManager.GetString("General_MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &apos;{0}&apos; must be installed for this feature to work.  Ensure that this service is available. HRESULT = 0x{1:X8}.
        /// </summary>
        internal static string General_MissingServiceWithHR {
            get {
                return ResourceManager.GetString("General_MissingServiceWithHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &apos;{0}&apos; does not implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string General_NoServiceInterface {
            get {
                return ResourceManager.GetString("General_NoServiceInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value: {0}..
        /// </summary>
        internal static string General_UnsupportedValue {
            get {
                return ResourceManager.GetString("General_UnsupportedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ignore.
        /// </summary>
        internal static string IgnoreCaption {
            get {
                return ResourceManager.GetString("IgnoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value of MessageDialogCommand..
        /// </summary>
        internal static string InvalidMessageDialogCommand {
            get {
                return ResourceManager.GetString("InvalidMessageDialogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value of MessageDialogCommandSet..
        /// </summary>
        internal static string InvalidMessageDialogCommandSet {
            get {
                return ResourceManager.GetString("InvalidMessageDialogCommandSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        internal static string NoCaption {
            get {
                return ResourceManager.GetString("NoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        internal static string OkCaption {
            get {
                return ResourceManager.GetString("OkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dialog page type {0} does not derive from DialogPage..
        /// </summary>
        internal static string Package_BadDialogPageType {
            get {
                return ResourceManager.GetString("Package_BadDialogPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution option name {0} is invalid.  It cannot contain &apos;.&apos;, &apos;/&apos; or other special characters..
        /// </summary>
        internal static string Package_BadOptionName {
            get {
                return ResourceManager.GetString("Package_BadOptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance {0} of extension point {1} cannot be obtained from the package {2}, or the extension is not of type {3}.\r\n{4}.
        /// </summary>
        internal static string Package_CannotGetExtensionPoint {
            get {
                return ResourceManager.GetString("Package_CannotGetExtensionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} already exists in the service container..
        /// </summary>
        internal static string Package_DuplicateService {
            get {
                return ResourceManager.GetString("Package_DuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested extension point was not recognized by this package..
        /// </summary>
        internal static string Package_ExtensionPointNotRecognized {
            get {
                return ResourceManager.GetString("Package_ExtensionPointNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested {0} extension point provider {1} was not found declared as package attribute..
        /// </summary>
        internal static string Package_ExtensionPointProviderNotFound {
            get {
                return ResourceManager.GetString("Package_ExtensionPointProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance ID {0} is invalid..
        /// </summary>
        internal static string Package_InvalidInstanceID {
            get {
                return ResourceManager.GetString("Package_InvalidInstanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service instance must derive from or implement {0}..
        /// </summary>
        internal static string Package_InvalidServiceInstance {
            get {
                return ResourceManager.GetString("Package_InvalidServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateToolWindow only creates Tool Windows derived from ToolWindowPane..
        /// </summary>
        internal static string Package_InvalidToolWindowClass {
            get {
                return ResourceManager.GetString("Package_InvalidToolWindowClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package requires that service &apos;{0}&apos; be installed.  Ensure that this service is available..
        /// </summary>
        internal static string Package_MissingService {
            get {
                return ResourceManager.GetString("Package_MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution option name {0} is already used by this package..
        /// </summary>
        internal static string Package_OptionNameUsed {
            get {
                return ResourceManager.GetString("Package_OptionNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page type {0} does not offer an empty constructor..
        /// </summary>
        internal static string Package_PageCtorMissing {
            get {
                return ResourceManager.GetString("Package_PageCtorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page type {0} does not implement {1}..
        /// </summary>
        internal static string Package_PageMissingInterface {
            get {
                return ResourceManager.GetString("Package_PageMissingInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page class {0} must derive from DialogPage..
        /// </summary>
        internal static string Package_PageNotDialogPage {
            get {
                return ResourceManager.GetString("Package_PageNotDialogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site has already been set on package {0}..
        /// </summary>
        internal static string Package_SiteAlreadySet {
            get {
                return ResourceManager.GetString("Package_SiteAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters {0} and {1} have incompatible types.
        /// </summary>
        internal static string Reg_ErrorIncompatibleParametersTypes {
            get {
                return ResourceManager.GetString("Reg_ErrorIncompatibleParametersTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters {0} and {1} have incompatible values.
        /// </summary>
        internal static string Reg_ErrorIncompatibleParametersValues {
            get {
                return ResourceManager.GetString("Reg_ErrorIncompatibleParametersValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Reg_ExtensionPoint_Notify {
            get {
                return ResourceManager.GetString("Reg_ExtensionPoint_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; specified in the {1} attribute does not implement the {2} interface..
        /// </summary>
        internal static string Reg_ExtensionPoint_TypeDoesNotImplementInterface {
            get {
                return ResourceManager.GetString("Reg_ExtensionPoint_TypeDoesNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoload package:         {0}.
        /// </summary>
        internal static string Reg_NotifyAutoLoad {
            get {
                return ResourceManager.GetString("Reg_NotifyAutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatable Object: {0}.
        /// </summary>
        internal static string Reg_NotifyCreateObject {
            get {
                return ResourceManager.GetString("Reg_NotifyCreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Extension: {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyEditorExtension {
            get {
                return ResourceManager.GetString("Reg_NotifyEditorExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Factory:   {0}.
        /// </summary>
        internal static string Reg_NotifyEditorFactory {
            get {
                return ResourceManager.GetString("Reg_NotifyEditorFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical View:     {0}.
        /// </summary>
        internal static string Reg_NotifyEditorView {
            get {
                return ResourceManager.GetString("Reg_NotifyEditorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extender:         {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyExtender {
            get {
                return ResourceManager.GetString("Reg_NotifyExtender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Product:   {0}, Version {1}.
        /// </summary>
        internal static string Reg_NotifyInstalledProduct {
            get {
                return ResourceManager.GetString("Reg_NotifyInstalledProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Product:   Using IVsInstalledProduct interface.
        /// </summary>
        internal static string Reg_NotifyInstalledProductInterface {
            get {
                return ResourceManager.GetString("Reg_NotifyInstalledProductInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Binding: {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyKeyBinding {
            get {
                return ResourceManager.GetString("Reg_NotifyKeyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Code Expansion: {0}.
        /// </summary>
        internal static string Reg_NotifyLanguageCodeExpansion {
            get {
                return ResourceManager.GetString("Reg_NotifyLanguageCodeExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Extension: {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyLanguageExtension {
            get {
                return ResourceManager.GetString("Reg_NotifyLanguageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageOptionCategory: {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyLanguageOptionCategory {
            get {
                return ResourceManager.GetString("Reg_NotifyLanguageOptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Option Page: {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyLanguageOptionPage {
            get {
                return ResourceManager.GetString("Reg_NotifyLanguageOptionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Service: {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyLanguageService {
            get {
                return ResourceManager.GetString("Reg_NotifyLanguageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadKey:          {0} {1}
        ///Version {2}
        ///Edition Required: {3}.
        /// </summary>
        internal static string Reg_NotifyLoadKey {
            get {
                return ResourceManager.GetString("Reg_NotifyLoadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu:             {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyMenuResource {
            get {
                return ResourceManager.GetString("Reg_NotifyMenuResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu:             {0}, {1}, {2}.
        /// </summary>
        internal static string Reg_NotifyMenuResourceWithMapping {
            get {
                return ResourceManager.GetString("Reg_NotifyMenuResourceWithMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Page:      {0}\{1}.
        /// </summary>
        internal static string Reg_NotifyOptionPage {
            get {
                return ResourceManager.GetString("Reg_NotifyOptionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package:          {0} {1}.
        /// </summary>
        internal static string Reg_NotifyPackage {
            get {
                return ResourceManager.GetString("Reg_NotifyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Factory:  {0}.
        /// </summary>
        internal static string Reg_NotifyProjectFactory {
            get {
                return ResourceManager.GetString("Reg_NotifyProjectFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Items:    {0}.
        /// </summary>
        internal static string Reg_NotifyProjectItems {
            get {
                return ResourceManager.GetString("Reg_NotifyProjectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service:          {0}.
        /// </summary>
        internal static string Reg_NotifyService {
            get {
                return ResourceManager.GetString("Reg_NotifyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statically Registered Toolbox Group: ID &quot;{0}&quot;, Name &quot;{1}&quot;.
        /// </summary>
        internal static string Reg_NotifyStaticToolboxGroup {
            get {
                return ResourceManager.GetString("Reg_NotifyStaticToolboxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statically Registered Toolbox Item: Group ID &quot;{0}&quot;, Item ID &quot;{1}&quot;, Item Name &quot;{2}&quot;.
        /// </summary>
        internal static string Reg_NotifyStaticToolboxItem {
            get {
                return ResourceManager.GetString("Reg_NotifyStaticToolboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Items:    Version {0} (Formats: {1}).
        /// </summary>
        internal static string Reg_NotifyToolboxItem {
            get {
                return ResourceManager.GetString("Reg_NotifyToolboxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Config:   {0}.
        /// </summary>
        internal static string Reg_NotifyToolboxItemConfiguration {
            get {
                return ResourceManager.GetString("Reg_NotifyToolboxItemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                    Filter: {0}.
        /// </summary>
        internal static string Reg_NotifyToolboxItemFilter {
            get {
                return ResourceManager.GetString("Reg_NotifyToolboxItemFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Item Type: {0}.
        /// </summary>
        internal static string Reg_NotifyToolboxItemType {
            get {
                return ResourceManager.GetString("Reg_NotifyToolboxItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox Page:     {0}.
        /// </summary>
        internal static string Reg_NotifyToolboxPage {
            get {
                return ResourceManager.GetString("Reg_NotifyToolboxPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolWindow:       {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyToolResource {
            get {
                return ResourceManager.GetString("Reg_NotifyToolResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Visibility:  {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyToolVisibility {
            get {
                return ResourceManager.GetString("Reg_NotifyToolVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIContext Rule: {0}, Expression: {1}.
        /// </summary>
        internal static string Reg_NotifyUIContextRule {
            get {
                return ResourceManager.GetString("Reg_NotifyUIContextRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Retry.
        /// </summary>
        internal static string RetryCaption {
            get {
                return ResourceManager.GetString("RetryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified run context is not allowed for JoinableTask instances..
        /// </summary>
        internal static string RunContextNotSafeForJoinableTasks {
            get {
                return ResourceManager.GetString("RunContextNotSafeForJoinableTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change selection. Selected objects are read only in this selection container..
        /// </summary>
        internal static string SelectionContainer_ReadOnlySelection {
            get {
                return ResourceManager.GetString("SelectionContainer_ReadOnlySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked on the wrong thread..
        /// </summary>
        internal static string Services_InvokedOnWrongThread {
            get {
                return ResourceManager.GetString("Services_InvokedOnWrongThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is unavailable..
        /// </summary>
        internal static string ServiceUnavailable_Format {
            get {
                return ResourceManager.GetString("ServiceUnavailable_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items in this view are no longer available..
        /// </summary>
        internal static string SolutionNavigator_ItemsNoLongerAvailable {
            get {
                return ResourceManager.GetString("SolutionNavigator_ItemsNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        internal static string SolutionNavigator_RelationshipLabel {
            get {
                return ResourceManager.GetString("SolutionNavigator_RelationshipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to identify the UI thread&apos;s Dispatcher object..
        /// </summary>
        internal static string ThreadHelper_UIThreadDispatcherUnavailable {
            get {
                return ResourceManager.GetString("ThreadHelper_UIThreadDispatcherUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid toolbox item ID: {0}..
        /// </summary>
        internal static string Toolbox_InvalidItemId {
            get {
                return ResourceManager.GetString("Toolbox_InvalidItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox item &quot;{0}&quot; not found on machine..
        /// </summary>
        internal static string Toolbox_ItemNotFound {
            get {
                return ResourceManager.GetString("Toolbox_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported toolbox format: {0}..
        /// </summary>
        internal static string Toolbox_UnsupportedFormat {
            get {
                return ResourceManager.GetString("Toolbox_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVsWindowFrame.GetProperty for VSFPROPID_InfoBarHost failed, and adding the info bar did not complete..
        /// </summary>
        internal static string ToolWindow_InfoBarHostFailed {
            get {
                return ResourceManager.GetString("ToolWindow_InfoBarHostFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SVsInfoBarUIFactory could not be created, and adding the info bar did not complete..
        /// </summary>
        internal static string ToolWindow_InfoBarUICreationFailed {
            get {
                return ResourceManager.GetString("ToolWindow_InfoBarUICreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same info bar cannot be added multiple times..
        /// </summary>
        internal static string ToolWindow_NoRepeatInfoBars {
            get {
                return ResourceManager.GetString("ToolWindow_NoRepeatInfoBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package property of the tool window should only be set by the creator of the tool window..
        /// </summary>
        internal static string ToolWindow_PackageOnlySetByCreator {
            get {
                return ResourceManager.GetString("ToolWindow_PackageOnlySetByCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolClsid cannot be added after the Frame is created.
        ///Add the toolClsid in the ToolWindow constructor..
        /// </summary>
        internal static string ToolWindow_TooLateToAddTool {
            get {
                return ResourceManager.GetString("ToolWindow_TooLateToAddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar cannot be added after the Frame is created.
        ///Add the ToolBar in the ToolWindow constructor..
        /// </summary>
        internal static string ToolWindow_TooLateToAddToolbar {
            get {
                return ResourceManager.GetString("ToolWindow_TooLateToAddToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating or deactivating known UIContexts is not allowed..
        /// </summary>
        internal static string UIContext_SetIsActiveNotAllowed {
            get {
                return ResourceManager.GetString("UIContext_SetIsActiveNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}:Unknown].
        /// </summary>
        internal static string UnknownBucketLabel {
            get {
                return ResourceManager.GetString("UnknownBucketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        internal static string YesCaption {
            get {
                return ResourceManager.GetString("YesCaption", resourceCulture);
            }
        }
    }
}
